language: php
sudo: false
dist: xenial
matrix:
  fast_finish: true
cache:
- vendor
- bin
php:
- 7.2
before_script:
- composer install
- mkdir -p build/logs
- touch /tmp/.htaccess
script: make tests
after_script:
- bin/coveralls -v
deploy:
  - provider: script
    skip_cleanup: true
    script: "make publish"
    on:
      tags: true
