# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"

services:
  app:
    image: wordpressdevelop/php:7.4-fpm
    restart: always
    depends_on:
      - db
      - phpmyadmin
      - web
      - mailhog
    working_dir: /workspace/wp-cfm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TEST_DB_NAME: wordpress_test
    volumes:
      - .:/workspace/wp-cfm:cached
      - ./tools/local-env:/app:cached
      - .:/app/wp-content/plugins/wp-cfm:ro,cached
      - ~/.composer:/root/.composer:cached
      - ~/.npm:/root/.npm:cached
    networks:
      - wpcfm-net

  web:
    image: httpd
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./tools/local-env:/app:cached
      - .:/app/wp-content/plugins/wp-cfm:ro,cached
      - ./tools/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro,cached
    networks:
      - wpcfm-net

  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpcfm-net

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      PMA_HOST: db
      APACHE_PORT: 8081
    networks:
      - wpcfm-net

  ## SMTP Server + Web Interface for viewing and testing emails during development.
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - wpcfm-net

volumes:
  db:

networks:
  wpcfm-net:

