name: Static Code Analysis

on:
  pull_request:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'

env:
  WP_MULTISITE: 0
  PHP_VERSION: '7.4'
  COMPOSER_VERSION: '2.5'
  ACTION_VERSION: 1

jobs:
  check_static_analysis:
    name: Setup & Perform Static Analysis

    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      if: ${{ !env.ACT }}
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    # https://github.com/marketplace/actions/cache
    - name: Cache Composer dependencies
      if: ${{ !env.ACT }}
      uses: actions/cache@v3
      env:
        composer-cache-name: cache-composer
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.composer-cache-name }}-php${{ env.PHP_VERSION }}-v${{ env.ACTION_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.composer-cache-name }}-php${{ env.PHP_VERSION }}-v${{ env.ACTION_VERSION }}-

    - name: Setup PHP & Composer Environment
      # https://github.com/marketplace/actions/setup-php-action
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ env.PHP_VERSION }}"
        tools: "composer:${{ env.COMPOSER_VERSION }}"

    - name: Environment Check
      run: php -v && composer --version

    - name: Install Composer Dependencies
      run: composer install

    - name: Perform Static Analysis
      run: composer analyze
